# Generated by Django 5.2.1 on 2025-06-07 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_collector_updated_at_alter_collector_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collector',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
