# Generated by Django 5.2.1 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_alter_collector_address_alter_collector_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='overall_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
