# Generated by Django 5.2.1 on 2025-07-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_salesrecord_gross_salesrecord_overall_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='gross',
        ),
    ]
