# Generated by Django 5.2.2 on 2025-07-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_remove_salesrecord_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='report',
            field=models.TextField(blank=True, help_text='Optional report or notes about this sales record', null=True),
        ),
    ]
